### ISSUE TITLE
Обновление структуры папок

### ISSUE THREAD

**Issue by onl1ner** [sparrowcode/tutorials#7]
### Привет!

Отличной идеей было создать данный репозиторий, теперь создавать туториалы на [sparrowcode](sparrowcode.io) стало очень удобно. 

Сейчас все туториалы находятся в одной папке с мета файлом _(возможно это было сделано для более легкого парсинга, но следующее предложение вроде не сильно усложняет задачу)_, хочу предложить разделить данное дело по папкам. Есть два варианта:

1. Генерировать мету для каждого туториала отдельно и распределять их по папкам
2. Просто разбить текущую структуру по двум папкам: `meta`, `articles`

### Зачем это надо?
Для чистоты и более удобного поддерживания. 

### Что лучше?
Я предпочитаю первый вариант, т.к. он изолирует туториалы друг от друга и при создании новой статьи вероятность случайного изменения метаданных предыдущих статей сводится к нулю.

### Примеры
Привожу примеры структуры папок для каждого варианта. 

**Мета для каждого туториала/статьи:**
```
ru/
├─ drag-and-drop-part-1/
│  ├─ article.md/
│  ├─ meta.json/
```
**Разбиваем на две папки: `meta`, `articles`:**
```
ru/
├─ meta/
│  ├─ list.json/
├─ articles/
│  ├─ drag-and-drop-part-1.md
│  ├─ edge-insets-uibutton.md
│  ├─ how-to-delete-userdefaults-on-macos-catalyst.md
```

**Comment by onl1ner** [comment]
Говорится про второй вариант, который я предложил?

**Comment by ivanvorobei** [comment]
Не-а, если взять файлы `list.json`, переименовать их в `list-en.json` и `list-ru.json` и поместить в корень. Как тебе такой вариант?

**Comment by ivanvorobei** [comment]
Скоро добавятся файлы со списком автором (зависит от локали) и файл с категориями (не зависит от локали). Наверное твой вариант первый идеально.

**Comment by onl1ner** [comment]
Да, тоже интересный вариант, но этот один файл будет разрастаться по мере добавления новых туториалов и процент случайного изменения также может возрасти _(даже если и не пройдет PR, все равно неприятный момент)_. Декомпозиция на папки под каждую статью кажутся довольно удобными, т.к. они изолированы и их можно использовать без обращения к какому-то внешнему файлу.

**Comment by ivanvorobei** [comment]
Сможешь провернуть первый вариант?

**Comment by onl1ner** [comment]
Да, в свободное время могу заняться, открою PR, если кто-то не реализует раньше. Парсинг на фронте как у тебя происходит? Спрашиваю к тому, чтобы реализовать максимально безболезненно

**Comment by ivanvorobei** [comment]
Сделал
